// Copyright 2010, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// Author: vladl@google.com (Vlad Losev)
//
// Tests for Google Test itself. Tests in this file throw C++ or SEH
// exceptions, and the output is verified by gtest_catch_exceptions_test.py.

#include "gtest/gtest.h"

#include <stdio.h>  // NOLINT
#include <stdlib.h>  // For exit().

#if GTEST_HAS_SEH
# include <windows.h>
#endif

#if GTEST_HAS_EXCEPTIONS
# include <exception>  // For set_terminate().
# include <stdexcept>
#endif

using testing::Test;

#if GTEST_HAS_SEH

class SehExceptionInConstructorTest : public Test ***REMOVED***
 public:
  SehExceptionInConstructorTest() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInConstructorTest, ThrowsExceptionInConstructor) ***REMOVED******REMOVED***

class SehExceptionInDestructorTest : public Test ***REMOVED***
 public:
  ~SehExceptionInDestructorTest() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInDestructorTest, ThrowsExceptionInDestructor) ***REMOVED******REMOVED***

class SehExceptionInSetUpTestCaseTest : public Test ***REMOVED***
 public:
  static void SetUpTestCase() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInSetUpTestCaseTest, ThrowsExceptionInSetUpTestCase) ***REMOVED******REMOVED***

class SehExceptionInTearDownTestCaseTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInTearDownTestCaseTest, ThrowsExceptionInTearDownTestCase) ***REMOVED******REMOVED***

class SehExceptionInSetUpTest : public Test ***REMOVED***
 protected:
  virtual void SetUp() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInSetUpTest, ThrowsExceptionInSetUp) ***REMOVED******REMOVED***

class SehExceptionInTearDownTest : public Test ***REMOVED***
 protected:
  virtual void TearDown() ***REMOVED*** RaiseException(42, 0, 0, NULL); ***REMOVED***
***REMOVED***;

TEST_F(SehExceptionInTearDownTest, ThrowsExceptionInTearDown) ***REMOVED******REMOVED***

TEST(SehExceptionTest, ThrowsSehException) ***REMOVED***
  RaiseException(42, 0, 0, NULL);
***REMOVED***

#endif  // GTEST_HAS_SEH

#if GTEST_HAS_EXCEPTIONS

class CxxExceptionInConstructorTest : public Test ***REMOVED***
 public:
  CxxExceptionInConstructorTest() ***REMOVED***
    // Without this macro VC++ complains about unreachable code at the end of
    // the constructor.
    GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(
        throw std::runtime_error("Standard C++ exception"));
  ***REMOVED***

  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInConstructorTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInConstructorTest() ***REMOVED***
    ADD_FAILURE() << "CxxExceptionInConstructorTest destructor "
                  << "called unexpectedly.";
  ***REMOVED***

  virtual void SetUp() ***REMOVED***
    ADD_FAILURE() << "CxxExceptionInConstructorTest::SetUp() "
                  << "called unexpectedly.";
  ***REMOVED***

  virtual void TearDown() ***REMOVED***
    ADD_FAILURE() << "CxxExceptionInConstructorTest::TearDown() "
                  << "called unexpectedly.";
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInConstructorTest, ThrowsExceptionInConstructor) ***REMOVED***
  ADD_FAILURE() << "CxxExceptionInConstructorTest test body "
                << "called unexpectedly.";
***REMOVED***

// Exceptions in destructors are not supported in C++11.
#if !defined(__GXX_EXPERIMENTAL_CXX0X__) &&  __cplusplus < 201103L
class CxxExceptionInDestructorTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInDestructorTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInDestructorTest() ***REMOVED***
    GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(
        throw std::runtime_error("Standard C++ exception"));
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInDestructorTest, ThrowsExceptionInDestructor) ***REMOVED******REMOVED***
#endif  // C++11 mode

class CxxExceptionInSetUpTestCaseTest : public Test ***REMOVED***
 public:
  CxxExceptionInSetUpTestCaseTest() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTestCaseTest constructor "
           "called as expected.\n");
  ***REMOVED***

  static void SetUpTestCase() ***REMOVED***
    throw std::runtime_error("Standard C++ exception");
  ***REMOVED***

  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTestCaseTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInSetUpTestCaseTest() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTestCaseTest destructor "
           "called as expected.\n");
  ***REMOVED***

  virtual void SetUp() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTestCaseTest::SetUp() "
           "called as expected.\n");
  ***REMOVED***

  virtual void TearDown() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTestCaseTest::TearDown() "
           "called as expected.\n");
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInSetUpTestCaseTest, ThrowsExceptionInSetUpTestCase) ***REMOVED***
  printf("%s",
         "CxxExceptionInSetUpTestCaseTest test body "
         "called as expected.\n");
***REMOVED***

class CxxExceptionInTearDownTestCaseTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED***
    throw std::runtime_error("Standard C++ exception");
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInTearDownTestCaseTest, ThrowsExceptionInTearDownTestCase) ***REMOVED******REMOVED***

class CxxExceptionInSetUpTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInSetUpTest() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTest destructor "
           "called as expected.\n");
  ***REMOVED***

  virtual void SetUp() ***REMOVED*** throw std::runtime_error("Standard C++ exception"); ***REMOVED***

  virtual void TearDown() ***REMOVED***
    printf("%s",
           "CxxExceptionInSetUpTest::TearDown() "
           "called as expected.\n");
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInSetUpTest, ThrowsExceptionInSetUp) ***REMOVED***
  ADD_FAILURE() << "CxxExceptionInSetUpTest test body "
                << "called unexpectedly.";
***REMOVED***

class CxxExceptionInTearDownTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInTearDownTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInTearDownTest() ***REMOVED***
    printf("%s",
           "CxxExceptionInTearDownTest destructor "
           "called as expected.\n");
  ***REMOVED***

  virtual void TearDown() ***REMOVED***
    throw std::runtime_error("Standard C++ exception");
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInTearDownTest, ThrowsExceptionInTearDown) ***REMOVED******REMOVED***

class CxxExceptionInTestBodyTest : public Test ***REMOVED***
 public:
  static void TearDownTestCase() ***REMOVED***
    printf("%s",
           "CxxExceptionInTestBodyTest::TearDownTestCase() "
           "called as expected.\n");
  ***REMOVED***

 protected:
  ~CxxExceptionInTestBodyTest() ***REMOVED***
    printf("%s",
           "CxxExceptionInTestBodyTest destructor "
           "called as expected.\n");
  ***REMOVED***

  virtual void TearDown() ***REMOVED***
    printf("%s",
           "CxxExceptionInTestBodyTest::TearDown() "
           "called as expected.\n");
  ***REMOVED***
***REMOVED***;

TEST_F(CxxExceptionInTestBodyTest, ThrowsStdCxxException) ***REMOVED***
  throw std::runtime_error("Standard C++ exception");
***REMOVED***

TEST(CxxExceptionTest, ThrowsNonStdCxxException) ***REMOVED***
  throw "C-string";
***REMOVED***

// This terminate handler aborts the program using exit() rather than abort().
// This avoids showing pop-ups on Windows systems and core dumps on Unix-like
// ones.
void TerminateHandler() ***REMOVED***
  fprintf(stderr, "%s\n", "Unhandled C++ exception terminating the program.");
  fflush(NULL);
  exit(3);
***REMOVED***

#endif  // GTEST_HAS_EXCEPTIONS

int main(int argc, char** argv) ***REMOVED***
#if GTEST_HAS_EXCEPTIONS
  std::set_terminate(&TerminateHandler);
#endif
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
***REMOVED***
